apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2020-04-13T21:50:56Z"
  generation: 6
  labels:
    app: docker-demo
  name: docker-demo
  namespace: default
  resourceVersion: "2306174"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/docker-demo
  uid: dae17898-7dd0-11ea-877e-42010a80009d
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: docker-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: docker-demo
    spec:
      containers:
      - image: asad02/docker-demo:0.0.2-RELEASE
        imagePullPolicy: IfNotPresent
        name: docker-demo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-04-19T20:44:37Z"
    lastUpdateTime: "2020-04-19T20:44:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-13T21:50:56Z"
    lastUpdateTime: "2020-04-19T20:48:55Z"
    message: ReplicaSet "docker-demo-78b945864d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
