apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  annotations:
  labels:
    app: docker-demo
  name: docker-demo
  namespace: default
spec:
  replicas: 3
  minReadySeconds: 45
  selector:
    matchLabels:
      app: docker-demo
#  strategy:
#    rollingUpdate:
#      maxSurge: 25%
#      maxUnavailable: 25%
#    type: RollingUpdate
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
        - image: asad02/docker-demo:0.0.3-RELEASE
          imagePullPolicy: IfNotPresent
          name: docker-demo
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-demo
  name: docker-demo
  namespace: default
spec:
  ports:
    - nodePort: 32377
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: docker-demo
  sessionAffinity: None
  type: LoadBalancer