apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-13T21:55:07Z"
  labels:
    app: docker-demo
  name: docker-demo
  namespace: default
  resourceVersion: "576318"
  selfLink: /api/v1/namespaces/default/services/docker-demo
  uid: 702eff0b-7dd1-11ea-877e-42010a80009d
spec:
  clusterIP: 10.0.12.7
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32377
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: docker-demo
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.226.5.226
